const products = [
    {
      _id: '1',
      name: 'Classic Cotton Baseball Cap',
      image: '/images/hat.jpg',
      description:
        'A classic six-panel baseball cap made from breathable cotton. Adjustable strap for a custom fit and embroidered logo for a timeless style.',
      brand: 'New Era',
      category: 'Clothing',
      price: 24.99,
      countInStock: 0,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '2',
      name: 'Men’s Slim Fit Oxford Shirt',
      image: '/images/shirt.jpg',
      description:
        'Tailored for a modern silhouette, this slim fit oxford shirt is crafted from soft, breathable cotton. Button-down collar and chest pocket.',
      brand: 'Calvin Klein',
      category: 'Clothing',
      price: 54.99,
      countInStock: 0,
      rating: 4.0,
      numReviews: 8,
    },
    {
      _id: '3',
      name: 'Stretch Denim Jeans',
      image: '/images/pants.jpg',
      description:
        'Durable and comfortable stretch denim jeans with a slim tapered leg. Designed for all-day wear with reinforced stitching.',
      brand: 'Levi’s',
      category: 'Clothing',
      price: 69.99,
      countInStock: 5,
      rating: 3,
      numReviews: 12,
    },
    {
      _id: '4',
      name: 'Athletic Performance Shorts',
      image: '/images/shorts.jpg',
      description:
        'Lightweight, moisture-wicking performance shorts with built-in mesh lining. Ideal for workouts or casual wear.',
      brand: 'Nike',
      category: 'Clothing',
      price: 39.99,
      countInStock: 11,
      rating: 5,
      numReviews: 12,
    },
    {
      _id: '5',
      name: 'Water-Resistant Hooded Jacket',
      image: '/images/jacket.jpg',
      description:
        'Stay dry and stylish with this water-resistant jacket. Adjustable hood, zip pockets, and lightweight insulation for transitional weather.',
      brand: 'The North Face',
      category: 'Clothing',
      price: 119.99,
      countInStock: 7,
      rating: 3.5,
      numReviews: 10,
    },
    // {
    //   _id: '6',
    //   name: 'Men’s Running Shoes',
    //   image: '/images/shoes.jpg',
    //   description:
    //     'Responsive cushioning and breathable mesh make these running shoes ideal for both beginners and seasoned runners. Rubber outsole for extra grip.',
    //   brand: 'Adidas',
    //   category: 'Clothing',
    //   price: 89.99,
    //   countInStock: 0,
    //   rating: 4,
    //   numReviews: 12,
    // },
    // {
    //   _id: '7',
    //   name: 'Wool Blend Beanie',
    //   image: '/images/beanie.jpg',
    //   description:
    //     'Stay warm with this soft wool blend beanie. Ribbed knit and snug fit provide comfort and insulation in colder weather.',
    //   brand: 'Carhartt',
    //   category: 'Clothing',
    //   price: 19.99,
    //   countInStock: 8,
    //   rating: 4.8,
    //   numReviews: 6,
    // },
    // {
    //   _id: '8',
    //   name: 'Women’s Linen V-Neck Blouse',
    //   image: '/images/blouse.jpg',
    //   description:
    //     'This breezy linen blouse features a flattering V-neck and relaxed silhouette, ideal for warm days or layering.',
    //   brand: 'Madewell',
    //   category: 'Clothing',
    //   price: 44.99,
    //   countInStock: 6,
    //   rating: 4.2,
    //   numReviews: 9,
    // },
    // {
    //   _id: '9',
    //   name: 'Cargo Utility Pants',
    //   image: '/images/cargo.jpg',
    //   description:
    //     'Functional and stylish, these cargo pants feature multiple pockets, reinforced knees, and a tapered fit for an urban edge.',
    //   brand: 'Dickies',
    //   category: 'Clothing',
    //   price: 59.99,
    //   countInStock: 4,
    //   rating: 3.9,
    //   numReviews: 11,
    // },
    // {
    //   _id: '10',
    //   name: 'Casual Cotton Chino Shorts',
    //   image: '/images/chinoshorts.jpg',
    //   description:
    //     'Made from breathable cotton twill, these chino shorts offer a clean look with a relaxed fit and button-front closure.',
    //   brand: 'Gap',
    //   category: 'Clothing',
    //   price: 34.99,
    //   countInStock: 12,
    //   rating: 4.3,
    //   numReviews: 7,
    // },
    // {
    //   _id: '11',
    //   name: 'Fleece Zip-Up Hoodie',
    //   image: '/images/hoodie.jpg',
    //   description:
    //     'A versatile zip-up fleece hoodie with a soft interior and front pockets. Perfect for layering during chilly seasons.',
    //   brand: 'Champion',
    //   category: 'Clothing',
    //   price: 49.99,
    //   countInStock: 9,
    //   rating: 4.6,
    //   numReviews: 10,
    // },
    // {
    //   _id: '12',
    //   name: 'Women’s White Low-Top Sneakers',
    //   image: '/images/whitesneakers.jpg',
    //   description:
    //     'These clean, minimalist low-top sneakers are perfect for everyday wear. Cushioned insole and rubber sole for comfort and grip.',
    //   brand: 'Vans',
    //   category: 'Clothing',
    //   price: 64.99,
    //   countInStock: 3,
    //   rating: 4.1,
    //   numReviews: 13,
    // },
  ];
  
  export default products;
  